config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: %i[edit update] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show; end

  def edit; end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to @list
    else
      render 'new'
    end
  end

  # def create
  #   list = List.new(list_params)
  #   list.save
  #   redirect_to lists_path
  # end

  # def edit
  # end

  # def update
  #   @list.update(list_params)
  #   redirect_to list_path(@list)
  # end

  # def destroy
  #   @list.destroy
  #   redirect_to lists_path
  # end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
# frozen_string_literal: true

module BookmarksHelper
end

app/helpers/list_helper.rb
# frozen_string_literal: true

module ListHelper
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
end

app/helpers/movies_helper.rb
# frozen_string_literal: true

module MoviesHelper
end

app/views/bookmarks/lists.html.erb
<h1>Bookmarks#lists</h1>
<p>Find me in app/views/bookmarks/lists.html.erb</p>

app/views/bookmarks/movies.html.erb
<h1>Bookmarks#movies</h1>
<p>Find me in app/views/bookmarks/movies.html.erb</p>

app/views/bookmarks/new.html.erb
new.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body class="container bg-light">
    <h1 class="text-center">AllMovies.com</h1>
    <h2 class="text-center">Find all the best movies to watch</h2>
    <!-- Navbar Implementation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-brand">
      <%= link_to 'My list' , lists_path %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <div class="nav-link">
            <%= link_to 'Create a new list', new_list_path %>
          </div>
        </li>
      </ul>
    </div>
  </nav>

    <%= yield %>

    <!-- Afficher tous les films -->
  </body>
</html>

app/views/lists/index.html.erb
  <!-- Banner Style -->
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8bW92aWVzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60);">
  </div>

<!-- Card Design -->
<% @lists.each do |list| %>
  <div class="card" style="width: 18rem;">
    <%= list.poster_url %>
    <div class="card-body">
      <h5 class="card-title"><%= list.name %></h5>
         <p><%= list.overview %></p>
      <p class="card-text"></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><%= list.rating %></li>
    </ul>
    <div class="card-body">
      <p class="card-link">More details on this movie <%= link_to 'More', list_path %></p>
      <p class="card-link">Delete this movie from your list?
        <%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    </div>
  </div>
<% end %>

app/views/lists/new.html.erb
<h1>New Movie</h1>

<%= simple_form_for([@bookmark, @list]) do |f| %>
    <%= f.input :name %>
    <%= f.submit "Add a movie name" %>
<% end %>

app/views/lists/show.html.erb
<h1></h1>